Mantaro/MantaroBot

src/main/java/net/kodehawa/mantarobot/commands/CurrencyCmds.java
src/main/java/net/kodehawa/mantarobot/commands/currency/item/Items.java

Some grammar/consistency and berserk effect fix

Minor shit

---

src/main/java/net/kodehawa/mantarobot/MantaroBot.java

I wanted to commit the smallest commit! Yay! c;

Removed uneccessary overhead due to lambdas

---

assets/mantaro/texts/pokemonguess.txt

Bleh, that extra `. Now it's removed!

Mime Jr. name fixed.

---

src/main/java/net/kodehawa/mantarobot/commands/DebugCmds.java

The rest of the pings have little emotes, maybe adding the :MantaroGasm: emote to ping with the `69` result  works :3
I know, basic but I wanted to feel speshul for making a pull request :3

Adding an emote to ~>ping

---

src/main/java/net/kodehawa/lib/imageboards/ImageboardAPI.java
src/main/java/net/kodehawa/mantarobot/MantaroBot.java
src/main/java/net/kodehawa/mantarobot/commands/CurrencyCmds.java
src/main/java/net/kodehawa/mantarobot/commands/ImageCmds.java
src/main/java/net/kodehawa/mantarobot/commands/currency/profile/Badge.java
src/main/java/net/kodehawa/mantarobot/commands/utils/birthday/BirthdayCacher.java
src/main/java/net/kodehawa/mantarobot/commands/utils/birthday/BirthdayTask.java
src/main/java/net/kodehawa/mantarobot/core/listeners/MantaroListener.java
src/main/java/net/kodehawa/mantarobot/utils/data/ConnectionWatcherDataManager.java

Basically makes birthdays less lazy/checks once a day at 00:00 if the user is a year older instead of only when the user talks.

Birthday rewrite

---

src/main/java/net/kodehawa/mantarobot/commands/UtilsCmds.java
src/main/java/net/kodehawa/mantarobot/commands/music/requester/AudioLoader.java

Update wiki command and fix a think in Audio Loader

---

src/main/java/net/kodehawa/mantarobot/commands/FunCmds.java

Remove Love checks

---

src/main/java/net/kodehawa/mantarobot/commands/CurrencyCmds.java

When you have to make the same change literally twice.. ._.

---

src/main/java/net/kodehawa/mantarobot/MantaroBot.java
src/main/java/net/kodehawa/mantarobot/commands/AnimeCmds.java
src/main/java/net/kodehawa/mantarobot/commands/DebugCmds.java
src/main/java/net/kodehawa/mantarobot/commands/GameCmds.java
src/main/java/net/kodehawa/mantarobot/commands/InfoCmds.java
src/main/java/net/kodehawa/mantarobot/commands/info/AsyncInfoMonitor.java
src/main/java/net/kodehawa/mantarobot/commands/moderation/MuteTask.java
src/main/java/net/kodehawa/mantarobot/commands/music/listener/VoiceChannelListener.java
src/main/java/net/kodehawa/mantarobot/core/MantaroCore.java
src/main/java/net/kodehawa/mantarobot/core/listeners/MantaroListener.java
src/main/java/net/kodehawa/mantarobot/core/listeners/command/CommandListener.java
src/main/java/net/kodehawa/mantarobot/core/listeners/events/PreLoadEvent.java
src/main/java/net/kodehawa/mantarobot/core/shard/ShardedMantaro.java
src/main/java/net/kodehawa/mantarobot/core/shard/jda/UnifiedJDA.java

Added handlers and stuff to account for it, so it should be fine, but needs more testing.
Waiting review from @natanbc

Make shard startup not lock the whole bot while starting up.

---

src/main/java/net/kodehawa/mantarobot/commands/currency/profile/Badge.java

English memes

---

src/main/java/net/kodehawa/mantarobot/commands/PlayerCmds.java

Yes its a one change commit, but since the role is gone this might be good to do.

Fix Helper badge

---

assets/mantaro/texts/animenames.txt

Skipped a lot of single named ones from the ones we were given due to not showing up as result at all or only second etc.

Add 68 new Characters to Anime game

---

src/main/resources/assets/languages/README.md
src/main/resources/assets/languages/de_DE.json

German translation

---

src/main/resources/assets/languages/de_DE.json

Hopefully, without messing up something - Github is confusing

Updated and fixed de_DE

---

src/main/resources/assets/languages/de_DE.json
src/main/resources/assets/languages/en_US.json

de_DE Update & en_US Fixes

---

src/main/resources/assets/languages/lt_LT.json

btw i don't remember anything about the commits on Sep 15, 2018 lol

lt_LT | Finally, i'm back

---

src/main/resources/assets/languages/de_DE.json

"You had ### equipped, but had no ### equipped" -Translation mistakes 2k18

de_DE | Equipment update

---

src/main/resources/assets/languages/de_DE.json

Maybe the diff just explodes a bit 'cause of 9f4f84b... But only maybe... Ahem.

de_DE | Uhm... Well. Updates. And Indentation.

---

src/main/resources/assets/languages/de_DE.json

Wasn't quite sure with some of the ratelimit/mod quotes though

de_DE | Updates

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/documentation_issue.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.github/ISSUE_TEMPLATE/suggestion.md
src/main/java/net/kodehawa/mantarobot/commands/FunCmds.java

Title says everything so have a 🍪

Add issue templates & fix love command breaking from spoiler tags 

---

src/main/resources/assets/languages/de_DE.json

de_DE | Update

---

build.gradle
src/main/java/net/kodehawa/mantarobot/MantaroBot.java
src/main/java/net/kodehawa/mantarobot/commands/MusicCmds.java
src/main/java/net/kodehawa/mantarobot/commands/game/core/Game.java
src/main/java/net/kodehawa/mantarobot/commands/music/GuildMusicManager.java
src/main/java/net/kodehawa/mantarobot/commands/music/MantaroAudioManager.java
src/main/java/net/kodehawa/mantarobot/commands/music/listener/VoiceChannelListener.java
src/main/java/net/kodehawa/mantarobot/commands/music/requester/TrackScheduler.java
src/main/java/net/kodehawa/mantarobot/commands/music/utils/AudioCmdUtils.java
src/main/java/net/kodehawa/mantarobot/core/listeners/MantaroListener.java
src/main/java/net/kodehawa/mantarobot/core/shard/MantaroShard.java
src/main/java/net/kodehawa/mantarobot/data/Config.java

Should be 100% working. Needs a bit more testing though.

Lavalink Implementation.

---

src/main/resources/assets/languages/de_DE.json

Big oof. "it's"
(Also lost my 2FA on my 'Vrontis' Account, so memes.)

de_DE | Updated

---

src/main/resources/assets/languages/fr_FR.json

From the 831st line to the 1279th line.

Continuing translation fr_FR

---

src/main/resources/assets/languages/fr_FR.json

I translated all parts of the file which wasn't and corrected the mistakes of sense when there were.

Ending french translation

---

src/main/resources/assets/languages/fr_FR.json

I let behind me some spelling mistakes (forgetting some letters, some sentences didn't have any sense, etc.). I'm continuing huntingthem but it's pretty much done.

Some minor bug correction

---

src/main/resources/assets/languages/nl_NL.json

I was going to check how the bot works, found out there were some improvements to be made in the translations file.
Thought I'd make myself useful :)
Discord: Twhiz#6814

Did some corrections and some extra translations in the nl_NL file

---

README.md

Tidy and spell check Readme

---

FEATURES.md

Title? Also cloning commits with rebasing is fun and very working as intended.

Make features have more structure and be more visually appealing

---

src/main/resources/assets/languages/fr_FR.json

I translated all the new features and I've corrected some meaning which were a bit incorrect depending on the context and some spelling mistakes

Translating new features + some corrections

---

src/main/resources/assets/languages/de_DE.json
src/main/resources/assets/languages/en_US.json

As well as a few things fixed in en_US

Updates & fixes for German lang

---

src/main/java/net/kodehawa/mantarobot/commands/music/MantaroAudioManager.java
src/main/java/net/kodehawa/mantarobot/core/shard/Shard.java

Since I am not funny immersed in the project yet might be worth looking this over

Fix some mishaps 

---

src/main/java/net/kodehawa/mantarobot/commands/CurrencyCmds.java
src/main/resources/assets/languages/en_US.json

Fix ->useitem

---

build.gradle
src/main/java/net/kodehawa/mantarobot/MantaroBot.java
src/main/java/net/kodehawa/mantarobot/commands/CustomCmds.java
src/main/java/net/kodehawa/mantarobot/commands/DebugCmds.java
src/main/java/net/kodehawa/mantarobot/commands/LeaderboardCmd.java
src/main/java/net/kodehawa/mantarobot/commands/MusicCmds.java
src/main/java/net/kodehawa/mantarobot/commands/utils/birthday/BirthdayCacher.java
src/main/java/net/kodehawa/mantarobot/core/listeners/MantaroListener.java
src/main/java/net/kodehawa/mantarobot/core/modules/commands/i18n/I18nContext.java
src/main/java/net/kodehawa/mantarobot/db/ManagedDatabase.java
src/main/java/net/kodehawa/mantarobot/services/StatsPoster.java
src/main/java/net/kodehawa/mantarobot/services/entities/ShardStats.java
src/main/java/net/kodehawa/mantarobot/utils/Utils.java

@adriantodt rewrote the whole rethinkdb driver on 2.4.1 and 2.4.2, so we give it a go here. Should be faster and more stable overall, but will need a small test in prod before it gets merged.

Update rethinkdb driver to 2.4.2

---

src/main/java/net/kodehawa/mantarobot/commands/MusicCmds.java

randomly stumbled upon it, not sure if it fixes some functionality

fixed soundcloud typo

---

README.md

Add Hax as wiki maintainer & shift me to server maintainer.

Update Important Contributors

---

src/main/java/net/kodehawa/mantarobot/core/MantaroCore.java

Natan: "lower thread count by like 1700+" part 2: electric boogaloo

Lower thread count

---

src/main/resources/assets/languages/README.md

Also, do we want to update contributors at some point?

Update languages/README because of crowdin and stuff

---

FEATURES.md

- remove old command,
- remove duplicates
- and intellij but it is grammarly

Clean up Features:

---

src/main/java/net/kodehawa/mantarobot/commands/currency/pets/HousePet.java
src/main/java/net/kodehawa/mantarobot/commands/currency/pets/HousePetType.java
src/main/java/net/kodehawa/mantarobot/utils/commands/EmoteReference.java
src/main/resources/assets/languages/en_US.json

Can't remember how we got here, but well, it was done.

Add(pet): Add pet rock

---

src/main/resources/assets/languages/en_US.json

Should fix both issues raised by Blue. cc #contributors

Fix(locale): Fix missing dot and misplaced space

---

src/main/resources/assets/languages/ar_SA.json
src/main/resources/assets/languages/cs_CZ.json
src/main/resources/assets/languages/de_DE.json
src/main/resources/assets/languages/es_ES.json
src/main/resources/assets/languages/fil_PH.json
src/main/resources/assets/languages/fr_FR.json
src/main/resources/assets/languages/hi_IN.json
src/main/resources/assets/languages/hu_HU.json
src/main/resources/assets/languages/ja_JP.json
src/main/resources/assets/languages/ko_KR.json
src/main/resources/assets/languages/lt_LT.json
src/main/resources/assets/languages/ms_MY.json
src/main/resources/assets/languages/nl_NL.json
src/main/resources/assets/languages/pl_PL.json
src/main/resources/assets/languages/pt_BR.json
src/main/resources/assets/languages/ru_RU.json
src/main/resources/assets/languages/tr_TR.json
src/main/resources/assets/languages/tsu_TSU.json
src/main/resources/assets/languages/vi_VN.json
src/main/resources/assets/languages/zh_CN.json
src/main/resources/assets/languages/zh_TW.json

Reverts Mantaro/MantaroBot#404

Revert "New Crowdin updates"

---

src/main/resources/assets/languages/ar_SA.json
src/main/resources/assets/languages/cs_CZ.json
src/main/resources/assets/languages/de_DE.json
src/main/resources/assets/languages/es_ES.json
src/main/resources/assets/languages/fil_PH.json
src/main/resources/assets/languages/fr_FR.json
src/main/resources/assets/languages/hi_IN.json
src/main/resources/assets/languages/hu_HU.json
src/main/resources/assets/languages/ja_JP.json
src/main/resources/assets/languages/ko_KR.json
src/main/resources/assets/languages/lt_LT.json
src/main/resources/assets/languages/ms_MY.json
src/main/resources/assets/languages/nl_NL.json
src/main/resources/assets/languages/pl_PL.json
src/main/resources/assets/languages/pt_BR.json
src/main/resources/assets/languages/ru_RU.json
src/main/resources/assets/languages/tr_TR.json
src/main/resources/assets/languages/tsu_TSU.json
src/main/resources/assets/languages/vi_VN.json
src/main/resources/assets/languages/zh_CN.json
src/main/resources/assets/languages/zh_TW.json

Reverts Mantaro/MantaroBot#411

Revert "Revert "New Crowdin updates""

---

src/main/java/net/kodehawa/mantarobot/commands/BirthdayCmd.java
src/main/java/net/kodehawa/mantarobot/commands/CurrencyActionCmds.java
src/main/java/net/kodehawa/mantarobot/commands/ItemCmds.java
src/main/java/net/kodehawa/mantarobot/commands/PetCmds.java
src/main/java/net/kodehawa/mantarobot/commands/currency/item/ItemReference.java
src/main/java/net/kodehawa/mantarobot/commands/currency/item/special/Axe.java
src/main/java/net/kodehawa/mantarobot/commands/currency/item/special/FishRod.java
src/main/java/net/kodehawa/mantarobot/commands/currency/item/special/Pickaxe.java
src/main/java/net/kodehawa/mantarobot/commands/currency/item/special/helpers/Attribute.java
src/main/java/net/kodehawa/mantarobot/commands/currency/item/special/helpers/Type.java
src/main/java/net/kodehawa/mantarobot/commands/currency/pets/HousePet.java
src/main/java/net/kodehawa/mantarobot/commands/currency/pets/PetChoice.java
src/main/java/net/kodehawa/mantarobot/commands/utils/birthday/BirthdayCacher.java
src/main/java/net/kodehawa/mantarobot/commands/utils/birthday/BirthdayTask.java
src/main/java/net/kodehawa/mantarobot/db/entities/helpers/PlayerData.java
src/main/java/net/kodehawa/mantarobot/options/BirthdayOptions.java
src/main/java/net/kodehawa/mantarobot/utils/Utils.java
src/main/java/net/kodehawa/mantarobot/utils/commands/EmoteReference.java
src/main/resources/assets/languages/en_US.json

Title. Should have *some* memory savings.

Use longs to store IDs on birthday stuff

---

src/main/java/net/kodehawa/mantarobot/commands/CurrencyCmds.java
src/main/java/net/kodehawa/mantarobot/commands/ItemCmds.java
src/main/java/net/kodehawa/mantarobot/commands/PetCmds.java
src/main/java/net/kodehawa/mantarobot/commands/PlayerCmds.java
src/main/java/net/kodehawa/mantarobot/commands/currency/item/ItemHelper.java
src/main/java/net/kodehawa/mantarobot/commands/currency/pets/HousePetType.java
src/main/java/net/kodehawa/mantarobot/core/CommandRegistry.java
src/main/java/net/kodehawa/mantarobot/core/command/meta/Options.java
src/main/java/net/kodehawa/mantarobot/core/command/processor/CommandProcessor.java
src/main/java/net/kodehawa/mantarobot/core/command/slash/AutocompleteContext.java
src/main/java/net/kodehawa/mantarobot/core/command/slash/SlashCommand.java
src/main/java/net/kodehawa/mantarobot/core/listeners/command/CommandListener.java
src/main/java/net/kodehawa/mantarobot/data/I18n.java
src/main/resources/assets/languages/en_US.json

adds autocompletion handling, we already use choices in a few places (and this also adds some more). However the true auto completion is nice for suggesting users, for instance, items to use, for which we cannot use choices.

add(autocompletion):
